version: "3.9"
services:
  web:
    container_name: server
    build: .
    depends_on: 
      - db
    # tries every 5 seconds to start python server only if db is running on port 5432, sleeps infinity
    command: bash -c "while !</dev/tcp/db/5432; do sleep 5; done; uvicorn main:app --reload && tail -F anything"
    environment: 
      - LOG_LEVEL=debug
      - mode=dev
      - POSTGRES_USER=demouser
      - POSTGRES_DB=demo
      - POSTGRES_PASSWORD=password123
      - DATABASE_URL=postgresql://demouser:password123@db:5432/demo

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=demo
    logging:
      options:
        max-size: 10m
        max-file: "3"
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  logvolume01: {}